name: dart_samples
version: 0.0.1-dev
description: Samples for Dart
homepage: https://github.com/dart-lang/dart-samples
environment:
  sdk: '>=0.6.17'
dependencies:
  browser: any
  nedb:
    path: web/dragster/html/lib/nedb/
  hop: any
  html5lib: any
#  menu:
#    path: web/dragster/html/lib/menu/
