name: dart_samples
version: 0.0.1-dev
description: Samples for Dart
homepage: https://github.com/dart-lang/dart-samples
environment:
  sdk: '>=0.6.17'
dependencies:
  browser: any
  vector_math: any
  hop: any
  path: any
  html5lib: any
  polymer: ">=0.10.0 <0.11.0"
dev_dependencies:
  unittest: ">=0.10.0 <0.11.0"
transformers:
- polymer:
    entry_points:
      - web/binding_data/index.html
      - web/binding_to_a_style_value/index.html
      - web/creating_an_element/index.html
      - web/creating_an_element_using_noscript/index.html
      - web/waiting_until_an_element_is_ready/index.html
      - web/publishing_properties/index.html
      - web/finding_shadow_dom_nodes_by_id/index.html
      - web/binding_with_built_in_elements/index.html